# FROM node:lts-alpine

# # install simple http server for serving static content
# RUN npm install -g http-server

# # make the 'app' folder the current working directory
# WORKDIR /app

# # copy both 'package.json' and 'package-lock.json' (if available)
# COPY package*.json ./

# # install project dependencies leaving out dev dependencies
# RUN npm install --production
# RUN npm install @vue/cli@3.7.0 -g

# # copy project files and folders to the current working directory (i.e. 'app' folder)
# COPY . .

# # build app for production with minification
# EXPOSE 8080
# CMD ["npm", "run", "serve"]

# CMD [ "http-server", "dist" ]

# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN rm -rf node_modules package-lock.json && npm install
#RUN export PATH="$(yarn global bin):$PATH"
RUN npm cache clean -f

RUN npm install
RUN npm install @vue/cli@3.7.0 -g
COPY . .
RUN npm run build
# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
